name: mp
channels:
  - open3d-admin
  - conda-forge
  - defaults
dependencies:
  - pip=20.2.2  
  - python=3.7.7
  - numpy=1.19.1
  - pandas=1.1.4
  - plyfile=0.7.2
  - pyyaml=5.3.1
  - tqdm=4.54.1
  - matplotlib=3.3.3 
  - open3d=0.11.2.0
  - pip:
    - opencv-python==4.2.0.34
    - mediapipe==0.8.4.2
    - addict==2.4.0
    - sklearn==0.0